project:
  type: website
  render:
    - "*.qmd"
    - "!rv/"

website:
  description: "Statistical modeling and causal inference, with applications in advertising effectiveness measurement."
  site-url: https://topazape.dev
  title: "topazape"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/topazape
      - icon: twitter-x
        href: https://x.com/topazape
      - icon: linkedin
        href: https://bra

format:
  html:
    theme:
      - litera
    css: styles.css

execute:
  freeze: auto
