project:
  type: website
  render:
    - "*.qmd"
    - "!rv/"

website:
  description: "Statistical modeling and causal inference, with applications in advertising effectiveness measurement."
  site-url: https://topazape.dev
  title: "topazape"
  navbar:
    left:
      - about.qmd
    right:
      - icon: github
        href: https://github.com/topazape
      - icon: twitter-x
        href: https://x.com/topazape
      - icon: linkedin
        href: https://www.linkedin.com/in/tomonori-kawai

format:
  html:
    theme:
      - litera
      - custom.scss
    mainfont: "Inter, sans-serif"
    monofont: "Fira Code, monospace"
    css: styles.css

execute:
  freeze: auto
