{
  "hash": "fd242e78b121b2286a9035362380e922",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: >-\n  Differential Attrition in Brand Lift: Diagnosing Selection Bias with Lee Bounds\ndescription: >-\n  Diagnose selection bias from differential survey response in Brand Lift studies using Lee bounds, with binary-outcome examples and reusable R code.\nimage: index_files/figure-html/fig-bounds-vs-p-1.png\ndate: \"2026-08-26\"\ncategories: [\"brand-lift\", \"statistics\", \"causal-inference\"]\n---\n\n\n\nEvery Brand Lift Study (BLS) 2×2 table is built from survey respondents, not from everyone who was surveyed.\nIf ad exposure changes who responds, the exposed and control groups are drawn from different subpopulations, and the risk ratio $\\widehat{RR}$ carries a selection bias that no CI method can remove.\n\nThis post introduces Lee bounds ([Lee 2009](https://doi.org/10.1111/j.1467-937X.2009.00536.x)) as a diagnostic for this problem.\nLee bounds quantify how large the bias could be under a monotonicity assumption, without modeling the selection mechanism.\nThe output is not a point estimate but a partially identified interval for the causal effect among always-responders: the subpopulation that would respond regardless of ad exposure.\nIf the interval excludes zero, the lift is robust.\nIf it spans zero, the naive $\\widehat{RR}$ may be an artifact of who showed up to answer the survey.\n\n## The selection problem in BLS\n\nA BLS campaign delivers surveys to $N_1$ exposed and $N_0$ control individuals.\nOf these, $n_1$ and $n_0$ respond.\nThe response rates are:\n\n$$\n  q_1 = \\frac{n_1}{N_1}, \\quad q_0 = \\frac{n_0}{N_0}\n$$\n\nThe 2×2 table analyzed in the [first post](/posts/bls-delta-method-rr/) is built from respondents only.\nIt records positive and negative responses among the $n_1$ and $n_0$ who answered, not among the $N_1$ and $N_0$ who were surveyed.\n\nIf $q_1 = q_0$, the respondents in each group are a random subset of their respective populations, and comparing $\\hat{p}_1$ to $\\hat{p}_0$ estimates the causal effect of exposure.\nIf $q_1 \\neq q_0$, the respondent subpopulations differ in composition.\nSome individuals respond only because they were exposed to the ad.\nThe difference $\\hat{p}_1 - \\hat{p}_0$ then conflates the effect of ad exposure on attitudes with the effect of ad exposure on who shows up in the data.\n\nThe CI methods from the previous posts handle sampling variability: the randomness in $\\hat{p}_1$ and $\\hat{p}_0$ given the respondent populations.\nSelection is a different problem: the non-randomness in who enters those populations in the first place.\n\n## Lee bounds: trimming under monotonicity\n\n### Setup and notation\n\nLet $Z \\in \\{0, 1\\}$ denote treatment assignment (control vs. exposed), $S \\in \\{0, 1\\}$ denote whether the individual responds to the survey, and $Y \\in \\{0, 1\\}$ denote the outcome (negative vs. positive response).\n$Y$ is observed only when $S = 1$.\n\nEach individual has potential outcomes $(S(0), S(1))$ for survey response and $(Y(0), Y(1))$ for the outcome.\nTreatment is randomly assigned (as in BLS), so $(S(z), Y(z))$ is independent of $Z$.\n\n### Principal strata\n\nThe pair $(S(0), S(1))$ partitions the population into four strata:\n\n  | Stratum           | $S(0)$ | $S(1)$ | Description                           |\n  | ----------------- | ------ | ------ | ------------------------------------- |\n  | Always-responders | 1      | 1      | Respond regardless of exposure        |\n  | Compliers         | 0      | 1      | Respond only when exposed             |\n  | Defiers           | 1      | 0      | Respond only when not exposed         |\n  | Never-responders  | 0      | 0      | Do not respond regardless of exposure |\n\n### Two assumptions\n\n**Random assignment.** $(S(z), Y(z)) \\perp Z$.\nThis holds by the BLS experimental design: exposed and control groups are assigned randomly.\n\n**Monotonicity.** $S(1) \\geq S(0)$ for all individuals.\nExposure does not cause anyone to stop responding.\nUnder this assumption, the defier stratum is empty.\n\nMonotonicity is not testable from the observed data.\nIt is adopted as a structural assumption about the survey response process: seeing an ad may prompt someone to engage with a subsequent survey about the ad, but it does not suppress the response of someone who would have responded anyway.\nFor BLS, this is an assumption rather than a fact: the reverse mechanism is constructible, since irritation with the ad could make someone decline a survey about it, and violations in that direction are outside what these bounds control.\nIf the observed response rates show $q_1 < q_0$, the assumption is applied in the reverse direction and the trimming moves to the control group.\nThe formulas below assume $q_1 \\geq q_0$.\n\n### Strata proportions\n\nUnder random assignment, $q_1 = P(S = 1 \\mid Z = 1) = P(S(1) = 1)$ and $q_0 = P(S = 1 \\mid Z = 0) = P(S(0) = 1)$.\nUnder monotonicity:\n\n$$\n  P(\\text{always-responder}) = P(S(0) = 1) = q_0\n$$\n\n$$\n  P(\\text{complier}) = P(S(1) = 1) - P(S(0) = 1) = q_1 - q_0\n$$\n\n$$\n  P(\\text{never-responder}) = 1 - P(S(1) = 1) = 1 - q_1\n$$\n\n### The trimming fraction\n\nAmong the exposed respondents ($Z = 1, S = 1$), the proportion who are compliers is:\n\n$$\n  p = \\frac{P(\\text{complier})}{P(S(1) = 1)} = \\frac{q_1 - q_0}{q_1}\n$$\n\nThe remaining fraction $1 - p = q_0 / q_1$ are always-responders.\nThe control respondents ($Z = 0, S = 1$) are all always-responders under monotonicity, since $S(0) = 1$ implies the individual is in the always-responder stratum.\n\nThe estimand is the average treatment effect among always-responders:\n\n$$\n  \\tau_{AR} = E[Y(1) - Y(0) \\mid \\text{always-responder}]\n$$\n\n$E[Y(0) \\mid \\text{always-responder}]$ is directly identified: it equals $E[Y \\mid Z = 0, S = 1]$, estimated by $\\hat{p}_0$, because all control respondents are always-responders.\n\n$E[Y(1) \\mid \\text{always-responder}]$ is not identified.\nThe observed $E[Y \\mid Z = 1, S = 1] = \\hat{p}_1$ is a mixture of always-responders and compliers, and the compliers' potential outcomes under exposure are unknown.\n\n### Bounds for binary outcomes\n\nTo bound $E[Y(1) \\mid \\text{always-responder}]$, consider two extreme assumptions about the compliers:\n\n**Lower bound.** Assume every complier has $Y(1) = 1$.\nThis attributes the maximum possible share of the observed positive rate to compliers, leaving the minimum for always-responders:\n\n$$\n  \\hat{p}_1^{L} = \\max\\!\\left( 0, \\;\\frac{\\hat{p}_1 - p}{1 - p} \\right)\n$$\n\n**Upper bound.** Assume every complier has $Y(1) = 0$.\nThe entire observed positive rate is attributed to always-responders:\n\n$$\n  \\hat{p}_1^{U} = \\min\\!\\left( 1, \\;\\frac{\\hat{p}_1}{1 - p} \\right)\n$$\n\nThe Lee bounds on $\\tau_{AR}$ are:\n\n$$\n  \\left[ \\hat{p}_1^{L} - \\hat{p}_0, \\quad \\hat{p}_1^{U} - \\hat{p}_0 \\right]\n$$\n\nThese bounds are sharp under the two assumptions (random assignment and monotonicity): no tighter bounds can be obtained without additional assumptions about the compliers.\n\n### When differential attrition vanishes\n\nIf $q_1 = q_0$, then $p = 0$, and $\\hat{p}_1^{L} = \\hat{p}_1^{U} = \\hat{p}_1$.\nThe bounds collapse to the point estimate $\\hat{p}_1 - \\hat{p}_0$, which is the naive estimator.\nThe naive $\\widehat{RR}$ is then unbiased for the always-responder effect, and the CIs from the previous posts apply directly.\n\n## Worked example: two scenarios\n\nTake $\\hat{p}_1 = 0.250$ and $\\hat{p}_0 = 0.200$, giving a naive absolute lift of $0.050$ and $\\widehat{RR} = 1.250$.\nThe same naive estimate leads to opposite diagnostic conclusions depending on the response rate gap.\n\n**Scenario A: large differential attrition** ($q_1 = 0.30$, $q_0 = 0.25$).\n\n$$\n  p = \\frac{0.30 - 0.25}{0.30} = 0.1667\n$$\n\n$$\n  \\hat{p}_1^{L} = \\frac{0.250 - 0.1667}{1 - 0.1667}\n                = \\frac{0.0833}{0.8333} = 0.100\n$$\n\n$$\n  \\hat{p}_1^{U} = \\frac{0.250}{0.8333} = 0.300\n$$\n\n  | Quantity                            | Value               |\n  | ----------------------------------- | ------------------: |\n  | Trimming fraction $p$               |             $0.167$ |\n  | $\\hat{p}_1^{L}$ (always-responders) |             $0.100$ |\n  | $\\hat{p}_1^{U}$ (always-responders) |             $0.300$ |\n  | Bounds on absolute lift             | $(-0.100,\\; 0.100)$ |\n  | Bounds on $RR$                      |  $(0.500,\\; 1.500)$ |\n\nThe lower bound on absolute lift is $-0.100$, and the lower bound on $RR$ is $0.500$.\nBoth span the null.\nA 5-percentage-point gap in response rates is enough to explain away the entire observed lift of 5%.\nThe positive rate in the exposed group could partly reflect compliers who are disproportionately likely to respond positively, not a genuine ad effect on always-responders.\n\n**Scenario B: small differential attrition** ($q_1 = 0.26$, $q_0 = 0.25$).\n\n$$\n  p = \\frac{0.26 - 0.25}{0.26} = 0.0385\n$$\n\n$$\n  \\hat{p}_1^{L} = \\frac{0.250 - 0.0385}{1 - 0.0385}\n                = \\frac{0.2115}{0.9615} = 0.220\n$$\n\n$$\n  \\hat{p}_1^{U} = \\frac{0.250}{0.9615} = 0.260\n$$\n\n  | Quantity                            | Value              |\n  | ----------------------------------- | -----------------: |\n  | Trimming fraction $p$               |            $0.038$ |\n  | $\\hat{p}_1^{L}$ (always-responders) |            $0.220$ |\n  | $\\hat{p}_1^{U}$ (always-responders) |            $0.260$ |\n  | Bounds on absolute lift             | $(0.020,\\; 0.060)$ |\n  | Bounds on $RR$                      | $(1.100,\\; 1.300)$ |\n\nThe lower bound on absolute lift is $0.020$: positive.\nThe lower bound on $RR$ is $1.100$: above $1$.\nThe lift is robust.\nEven under the worst-case assumption about compliers, the always-responder effect remains positive.\n\nBoth scenarios share the same naive estimates.\nThe diagnostic conclusion hinges entirely on the response rate gap $q_1 - q_0$, a quantity not present in the standard BLS 2×2 table.\n\n## Binary outcomes reduce resolution\n\nFor binary outcomes, the width of the Lee bounds on $E[Y(1) \\mid \\text{always-responder}]$ has a closed form.\nWhen both bounds are interior (strictly between 0 and 1):\n\n$$\n  \\hat{p}_1^{U} - \\hat{p}_1^{L} = \\frac{\\hat{p}_1}{1 - p}\n                                  - \\frac{\\hat{p}_1 - p}{1 - p}\n                                = \\frac{p}{1 - p}\n$$\n\nThe width depends only on the trimming fraction $p$.\nIt does not depend on $\\hat{p}_1$.\nThe width of the bounds on $\\tau_{AR}$ is the same, since $\\hat{p}_0$ cancels.\n\n\n::: {#tbl-bounds-width .cell tbl-cap='Lee bounds on absolute lift as a function of trimming fraction $p$. Fixed $\\hat{p}_1 = 0.250$, $\\hat{p}_0 = 0.200$; naive absolute lift = 0.050.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lzfavglbgm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#lzfavglbgm table {\n  font-family: Lora, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lzfavglbgm thead, #lzfavglbgm tbody, #lzfavglbgm tfoot, #lzfavglbgm tr, #lzfavglbgm td, #lzfavglbgm th {\n  border-style: none;\n}\n\n#lzfavglbgm p {\n  margin: 0;\n  padding: 0;\n}\n\n#lzfavglbgm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lzfavglbgm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lzfavglbgm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lzfavglbgm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lzfavglbgm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lzfavglbgm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lzfavglbgm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lzfavglbgm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lzfavglbgm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lzfavglbgm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lzfavglbgm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lzfavglbgm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lzfavglbgm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lzfavglbgm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lzfavglbgm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lzfavglbgm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lzfavglbgm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lzfavglbgm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lzfavglbgm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lzfavglbgm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lzfavglbgm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lzfavglbgm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lzfavglbgm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lzfavglbgm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lzfavglbgm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lzfavglbgm .gt_left {\n  text-align: left;\n}\n\n#lzfavglbgm .gt_center {\n  text-align: center;\n}\n\n#lzfavglbgm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lzfavglbgm .gt_font_normal {\n  font-weight: normal;\n}\n\n#lzfavglbgm .gt_font_bold {\n  font-weight: bold;\n}\n\n#lzfavglbgm .gt_font_italic {\n  font-style: italic;\n}\n\n#lzfavglbgm .gt_super {\n  font-size: 65%;\n}\n\n#lzfavglbgm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lzfavglbgm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lzfavglbgm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lzfavglbgm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lzfavglbgm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lzfavglbgm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lzfavglbgm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lzfavglbgm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lzfavglbgm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\"><span data-qmd-base64=\"JHAk\"><span class='gt_from_md'>\\(p\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"lower_lift\">Lower bound</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"upper_lift\">Upper bound</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"width\">Width</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.020</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">0.035</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.055</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.020</td></tr>\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.050</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">0.011</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.063</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.053</td></tr>\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.080</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">−0.015</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.072</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.087</td></tr>\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.100</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">−0.033</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.078</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.111</td></tr>\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.150</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">−0.082</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.094</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.176</td></tr>\n    <tr><td headers=\"p\" class=\"gt_row gt_right\">0.200</td>\n<td headers=\"lower_lift\" class=\"gt_row gt_right\">−0.138</td>\n<td headers=\"upper_lift\" class=\"gt_row gt_right\">0.112</td>\n<td headers=\"width\" class=\"gt_row gt_right\">0.250</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nAt $p = 0.10$, the width is $0.111$, more than twice the naive absolute lift of $0.050$.\nThe bounds cross zero at $p \\approx 0.063$, corresponding to a response rate ratio of $q_1 / q_0 \\approx 1.07$.\n\nThe crossing point has a closed form.\nThe lower bound on absolute lift is negative when:\n\n$$\n  \\frac{\\hat{p}_1 - p}{1 - p} < \\hat{p}_0 \\quad \\Longleftrightarrow \\quad p\n                              > \\frac{\\hat{p}_1 - \\hat{p}_0}{1 - \\hat{p}_0}\n$$\n\nFor $\\hat{p}_1 = 0.250$, $\\hat{p}_0 = 0.200$: the critical trimming fraction is $p^* = \\frac{0.050}{0.800} = 0.0625$.\n\nThis low threshold is a consequence of the binary outcome.\nTrimming operates by removing entire positive or negative responses.\nEach unit of trimming fraction shifts $\\hat{p}_1^L$ downward by a full step.\nWith continuous outcomes, trimming removes only tail observations, and the conditional mean shifts more gradually.\nFor BLS, where outcomes are always binary and typical lifts are in the range $\\hat{p}_1 - \\hat{p}_0 \\in [0.02, 0.05]$, even modest differential attrition can push the lower bound below zero.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Lee bounds on absolute lift as a function of trimming fraction $p$. The lower bound crosses zero at $p^* = 0.0625$. Naive absolute lift (dashed) is 0.050.](index_files/figure-html/fig-bounds-vs-p-1.png){#fig-bounds-vs-p width=672}\n:::\n:::\n\n\n## When Lee bounds add value\n\nLee bounds are a sensitivity analysis for selection bias, not a replacement for $\\widehat{RR}$.\nThey answer \"could the effect be zero despite what the naive estimate says?\"\nrather than \"what is the effect?\"\nMaking them a permanent pipeline component is hard to justify.\nThe computation is trivial, but the conceptual overhead of reporting partially identified intervals for every study is not.\n\nThe real value is as a one-time validation.\nAccumulate $q_1 - q_0$ across a set of studies.\nIf the distribution is tightly centered around zero, differential attrition is not a systematic concern, and the naive $\\widehat{RR}$ with its delta method CI can be trusted.\nIf specific campaign types show elevated $q_1 - q_0$, Lee bounds become a targeted diagnostic for those segments.\n\nRunning this validation requires survey delivery counts $N_1$ and $N_0$ alongside response counts $n_1$ and $n_0$.\nIf the pipeline stores only the 2×2 table of respondents, the response rate gap cannot be computed after the fact.\n\n## R code\n\n```r\nbls_lee_bounds <- function(q1, q0, p1_hat, p0_hat) {\n  # Formulas assume trimming on the exposed group\n  stopifnot(q1 >= q0)\n\n  # Trimming fraction\n  p <- (q1 - q0) / q1\n\n  # Bounds on E[Y(1) | always-responder]\n  p1_lower <- max(0, (p1_hat - p) / (1 - p))\n  p1_upper <- min(1, p1_hat / (1 - p))\n\n  # Bounds on treatment effect (absolute lift scale)\n  tau_lower <- p1_lower - p0_hat\n  tau_upper <- p1_upper - p0_hat\n\n  # Bounds on RR scale\n  rr_lower <- p1_lower / p0_hat\n  rr_upper <- p1_upper / p0_hat\n\n  list(\n    p = p,\n    p1_bounds = c(p1_lower, p1_upper),\n    lift_bounds = c(tau_lower, tau_upper),\n    rr_bounds = c(rr_lower, rr_upper)\n  )\n}\n\n# From raw counts:\n# N1, N0 = survey delivery counts\n# n1, n0 = respondent counts\n# x1, x0 = positive response counts\nbls_lee_bounds_counts <- function(N1, N0, n1, n0, x1, x0) {\n  q1 <- n1 / N1\n  q0 <- n0 / N0\n  p1_hat <- x1 / n1\n  p0_hat <- x0 / n0\n  bls_lee_bounds(q1, q0, p1_hat, p0_hat)\n}\n\n# Scenario A: large differential attrition\nbls_lee_bounds(q1 = 0.30, q0 = 0.25, p1_hat = 0.250, p0_hat = 0.200)\n\n# $p\n# [1] 0.1666667\n#\n# $p1_bounds\n# [1] 0.1 0.3\n#\n# $lift_bounds\n# [1] -0.1  0.1\n#\n# $rr_bounds\n# [1] 0.5 1.5\n\n# Scenario B: small differential attrition\nbls_lee_bounds(q1 = 0.26, q0 = 0.25, p1_hat = 0.250, p0_hat = 0.200)\n\n# $p\n# [1] 0.03846154\n#\n# $p1_bounds\n# [1] 0.22 0.26\n#\n# $lift_bounds\n# [1] 0.02 0.06\n#\n# $rr_bounds\n# [1] 1.1 1.3\n\n# Critical trimming fraction (bounds cross zero)\nbls_critical_p <- function(p1_hat, p0_hat) {\n  (p1_hat - p0_hat) / (1 - p0_hat)\n}\n\nbls_critical_p(0.250, 0.200)\n# [1] 0.0625\n```\n\nFor individual-level data $(Z_i, S_i, Y_i)$, the [leebounds](https://cran.r-project.org/package=leebounds) package computes Lee bounds with standard errors.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}