{
  "hash": "2582b6406385f1eb0ecd220343797370",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From Risk Ratios to Odds Ratios: Choosing an Aggregation Scale for Brand Lift\"\ndraft: true\ndraft-mode: unlinked\ndate: \"2026-08-12\"\ncategories: [\"brand-lift\", \"statistics\"]\n---\n\n\n\nThe first three posts in this series addressed a single-study question: did the campaign lift the outcome, and by how much? The [first post](/posts/bls-delta-method-rr/) derived a log-transform delta method CI for the risk ratio $RR$. The [second](/posts/bls-bootstrap-validation/) validated it by simulation and derived minimum sample sizes. The [third](/posts/bls-fieller-ci/) introduced Fieller's CI as an alternative that removes the Taylor approximation.\n\nThis post addresses a different question: how to compare and aggregate effects across studies with different baseline response rates. The scale used to report a single campaign's result to an advertiser and the scale used to pool results across studies serve different purposes and need not be the same.\n\n\n## The ceiling effect: RR and RD depend on the baseline\n\n$RR = \\frac{p_1}{p_0}$ is bounded above by $\\frac{1}{p_0}$, since $p_1 \\leq 1$. A study with $p_0 = 0.50$ can produce at most $RR = 2$. A study with $p_0 = 0.05$ can produce at most $RR = 20$. The maximum achievable $RR$ is a property of the baseline, not of the ad's effectiveness.\n\nThe risk difference $RD = p_1 - p_0$ has the same problem in the other direction: its maximum is $1 - p_0$. A study with $p_0 = 0.80$ can produce at most $RD = 0.20$, regardless of how effective the ad is.\n\nBoth $RR$ and $RD$ carry information about the baseline baked into their numerical value. Comparing $RR = 1.30$ from one study to $RR = 1.15$ from another and concluding the first ad was more effective requires the assumption that the two baselines impose similar constraints, which is rarely the case across BLS studies.\n\n\n## A baseline-free effect requires fixing a scale\n\nA measure that does not depend on $p_0$ requires a model assumption: that ad exposure shifts the outcome by a constant amount on some transformed scale. No transformation-free measure can achieve baseline independence; it must be imposed.\n\nThe logistic regression model assumes ad exposure shifts the log-odds of a positive response by a constant $\\beta$:\n\n$$\\text{logit}(p_1) = \\text{logit}(p_0) + \\beta$$\n\nUnder this model, $OR = \\exp(\\beta)$ is the same regardless of $p_0$. Given $p_0$ and $OR$, the exposed rate is:\n\n$$p_1 = \\frac{p_0 \\cdot OR}{1 - p_0 + p_0 \\cdot OR}$$\n\nPlugging in $OR = 1.30$:\n\n| $p_0$ | $p_1$  | $RR$  | $RD$  | $OR$ |\n|--------|--------|-------|-------|------|\n| 0.05   | 0.064  | 1.278 | 0.014 | 1.30 |\n| 0.10   | 0.126  | 1.262 | 0.026 | 1.30 |\n| 0.30   | 0.358  | 1.193 | 0.058 | 1.30 |\n| 0.50   | 0.565  | 1.130 | 0.065 | 1.30 |\n\n$OR$ is constant by construction. $RR$ decreases from 1.278 to 1.130 as $p_0$ increases: the ceiling compresses it. $RD$ increases from 0.014 to 0.065. The same logit-scale effect produces different $RR$ and $RD$ values at different baselines.\n\nThis is a model assumption, not a fact. Whether ad exposure truly operates on the logit scale is untestable from a single 2×2 table. The assumption is adopted because it makes cross-study comparison coherent, not because it is known to be correct.\n\n\n## The odds ratio and the variance of log(OR)\n\nThe odds ratio is defined as:\n\n$$OR = \\frac{p_1 / (1 - p_1)}{p_0 / (1 - p_0)}$$\n\nLabel the four cells of the 2×2 table as $a = x_1$, $b = n_1 - x_1$, $c = x_0$, $d = n_0 - x_0$. Then:\n\n$$\\widehat{OR} = \\frac{a \\cdot d}{b \\cdot c}$$\n\n$$\\log(\\widehat{OR}) = \\text{logit}(\\hat{p}_1) - \\text{logit}(\\hat{p}_0)$$\n\nApply the delta method to $g(p) = \\text{logit}(p) = \\log(p) - \\log(1-p)$. The derivative is $g'(p) = \\frac{1}{p(1-p)}$, so:\n\n$$\\text{Var}(\\text{logit}(\\hat{p})) \\approx \\frac{1}{[p(1-p)]^2} \\cdot \\frac{p(1-p)}{n} = \\frac{1}{n \\, p(1-p)}$$\n\nRewriting with cell counts $x = np$ and $n - x = n(1-p)$:\n\n$$\\text{Var}(\\text{logit}(\\hat{p})) = \\frac{1}{x} + \\frac{1}{n - x}$$\n\nSince $\\hat{p}_1$ and $\\hat{p}_0$ are independent, the variance of the difference is the sum:\n\n$$\\text{Var}(\\log(\\widehat{OR})) = \\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c} + \\frac{1}{d}$$\n\nThe [first post](/posts/bls-delta-method-rr/) derived $\\text{Var}(\\log(\\widehat{RR})) = \\frac{1}{x_1} - \\frac{1}{n_1} + \\frac{1}{x_0} - \\frac{1}{n_0}$, which can be rewritten as $\\frac{1}{a} - \\frac{1}{a+b} + \\frac{1}{c} - \\frac{1}{c+d}$. The variance of $\\log(\\widehat{OR})$ has a simpler form: four reciprocals with no subtraction.\n\n\n## Constructing the confidence interval for OR\n\nThe CI for $\\log(OR)$ follows the same structure as the log-transform CI for $RR$ from the first post: symmetric on the log scale, exponentiated back.\n\n$$\\log(\\widehat{OR}) \\pm z_{1-\\alpha/2} \\times \\sqrt{\\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c} + \\frac{1}{d}}$$\n\nExponentiating:\n\n$$\\left( \\widehat{OR} \\cdot \\exp(-z \\cdot SE), \\quad \\widehat{OR} \\cdot \\exp(+z \\cdot SE) \\right)$$\n\nwhere $SE = \\sqrt{\\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c} + \\frac{1}{d}}$.\n\nThe interval is always positive, asymmetric around $\\widehat{OR}$, and equivariant under inversion of the table.\n\n\n## Two properties that distinguish log(OR) from log(RR)\n\nBoth $\\log(\\widehat{RR})$ and $\\log(\\widehat{OR})$ have closed-form variance formulas derived from the delta method. Both support log-transform CIs, SQL implementation, and inverse-variance weighting. The closed-form variance is not a differentiator. Two properties are.\n\n**Baseline independence under logit additivity.** If ad exposure shifts log-odds by a constant $\\beta$, then $OR = \\exp(\\beta)$ does not depend on $p_0$. $RR$ and $RD$ do. This is the reason to use $\\log(OR)$ for cross-study aggregation: pooling $\\log(OR)$ values from studies with different baselines estimates a common effect on the logit scale. Pooling $\\log(RR)$ values conflates the ad effect with the baseline.\n\n**Transpose symmetry.** Swapping rows (exposed $\\leftrightarrow$ control) or columns (positive $\\leftrightarrow$ negative) in the 2×2 table maps $\\log(OR) \\to -\\log(OR)$: the sign flips, the magnitude is unchanged. $\\text{Var}(\\log(\\widehat{OR})) = \\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c} + \\frac{1}{d}$ is symmetric in all four cells, reflecting this property. $\\text{Var}(\\log(\\widehat{RR})) = \\frac{1}{a} - \\frac{1}{a+b} + \\frac{1}{c} - \\frac{1}{c+d}$ is not symmetric: swapping positive and negative produces a different variance, because $RR$ does not have transpose symmetry.\n\n\n## When the odds ratio approximates the risk ratio\n\nThe two measures are related by an identity:\n\n$$OR = RR \\times \\frac{1 - p_0}{1 - p_1}$$\n\nWhen both $p_0$ and $p_1$ are small, $\\frac{1 - p_0}{1 - p_1} \\approx 1$ and $OR \\approx RR$. This is the rare-disease assumption from epidemiology (Cornfield 1951).\n\nBLS response rates are not rare. Typical baselines range from 10% to 40%. At these levels, $OR$ and $RR$ diverge:\n\n| $p_0$ | $p_1$ | $RR$  | $OR$  |\n|--------|--------|-------|-------|\n| 0.02   | 0.024  | 1.200 | 1.205 |\n| 0.10   | 0.120  | 1.200 | 1.227 |\n| 0.30   | 0.360  | 1.200 | 1.313 |\n\nAt $p_0 = 0.30$ with $RR = 1.20$, the $OR$ is $1.31$, a 55% overstatement of the lift if misread as a risk ratio. In BLS contexts, $OR$ must not be interpreted as lift. The reporting scale for advertisers remains $RR - 1$ (relative lift) or $RD$ (absolute lift). $\\log(OR)$ serves a different purpose: aggregation.\n\n\n## Reporting scale vs. aggregation scale\n\nReport $RR - 1$ or $RD$ to advertisers. These are directly interpretable: \"the exposed group was 20% more likely to respond\" or \"the response rate increased by 3 percentage points.\" Aggregate in $\\log(OR)$. This separates the ad effect from the baseline, making it possible to compare and pool across studies with different baselines.\n\nThese are different scales for different purposes. Reporting in $RR$ and aggregating in $\\log(OR)$ is not inconsistent; it is a deliberate separation of concerns.\n\n\n## Worked example: three studies at different baselines\n\nFix $\\beta = \\log(1.30) = 0.2624$ and construct three synthetic studies with $n_1 = n_0 = 500$. Cell counts are $n \\times p$ rounded to the nearest integer.\n\n\n::: {#tbl-studies .cell tbl-cap='Three synthetic studies with constant log-odds effect $\\beta = \\log(1.30)$. OR is approximately constant; RR decreases with higher baseline.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"keggsqbfls\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#keggsqbfls table {\n  font-family: Lora, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#keggsqbfls thead, #keggsqbfls tbody, #keggsqbfls tfoot, #keggsqbfls tr, #keggsqbfls td, #keggsqbfls th {\n  border-style: none;\n}\n\n#keggsqbfls p {\n  margin: 0;\n  padding: 0;\n}\n\n#keggsqbfls .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#keggsqbfls .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#keggsqbfls .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#keggsqbfls .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#keggsqbfls .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#keggsqbfls .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#keggsqbfls .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#keggsqbfls .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#keggsqbfls .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#keggsqbfls .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#keggsqbfls .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#keggsqbfls .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#keggsqbfls .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#keggsqbfls .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#keggsqbfls .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#keggsqbfls .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#keggsqbfls .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#keggsqbfls .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#keggsqbfls .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#keggsqbfls .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#keggsqbfls .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#keggsqbfls .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#keggsqbfls .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#keggsqbfls .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#keggsqbfls .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#keggsqbfls .gt_left {\n  text-align: left;\n}\n\n#keggsqbfls .gt_center {\n  text-align: center;\n}\n\n#keggsqbfls .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#keggsqbfls .gt_font_normal {\n  font-weight: normal;\n}\n\n#keggsqbfls .gt_font_bold {\n  font-weight: bold;\n}\n\n#keggsqbfls .gt_font_italic {\n  font-style: italic;\n}\n\n#keggsqbfls .gt_super {\n  font-size: 65%;\n}\n\n#keggsqbfls .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#keggsqbfls .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#keggsqbfls .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#keggsqbfls .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#keggsqbfls .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#keggsqbfls .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#keggsqbfls .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#keggsqbfls .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#keggsqbfls div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"study\">Study</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p0\"><span data-qmd-base64=\"JHBfMCQ=\"><span class='gt_from_md'>\\(p_0\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p1\"><span data-qmd-base64=\"JHBfMSQ=\"><span class='gt_from_md'>\\(p_1\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a\"><span data-qmd-base64=\"JGEk\"><span class='gt_from_md'>\\(a\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"b\"><span data-qmd-base64=\"JGIk\"><span class='gt_from_md'>\\(b\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"c\"><span data-qmd-base64=\"JGMk\"><span class='gt_from_md'>\\(c\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"d\"><span data-qmd-base64=\"JGQk\"><span class='gt_from_md'>\\(d\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rr\"><span data-qmd-base64=\"JFJSJA==\"><span class='gt_from_md'>\\(RR\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"or\"><span data-qmd-base64=\"JE9SJA==\"><span class='gt_from_md'>\\(OR\\)</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">A</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.100</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.126</td>\n<td headers=\"a\" class=\"gt_row gt_right\">63</td>\n<td headers=\"b\" class=\"gt_row gt_right\">437</td>\n<td headers=\"c\" class=\"gt_row gt_right\">50</td>\n<td headers=\"d\" class=\"gt_row gt_right\">450</td>\n<td headers=\"rr\" class=\"gt_row gt_right\">1.260</td>\n<td headers=\"or\" class=\"gt_row gt_right\">1.297</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">B</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.300</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.358</td>\n<td headers=\"a\" class=\"gt_row gt_right\">179</td>\n<td headers=\"b\" class=\"gt_row gt_right\">321</td>\n<td headers=\"c\" class=\"gt_row gt_right\">150</td>\n<td headers=\"d\" class=\"gt_row gt_right\">350</td>\n<td headers=\"rr\" class=\"gt_row gt_right\">1.193</td>\n<td headers=\"or\" class=\"gt_row gt_right\">1.301</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">C</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.500</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.566</td>\n<td headers=\"a\" class=\"gt_row gt_right\">283</td>\n<td headers=\"b\" class=\"gt_row gt_right\">217</td>\n<td headers=\"c\" class=\"gt_row gt_right\">250</td>\n<td headers=\"d\" class=\"gt_row gt_right\">250</td>\n<td headers=\"rr\" class=\"gt_row gt_right\">1.132</td>\n<td headers=\"or\" class=\"gt_row gt_right\">1.304</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe log-odds effect is the same across all three studies by construction. $RR$ ranges from 1.132 (study C, $p_0 = 0.50$) to 1.260 (study A, $p_0 = 0.10$). Ranking by $RR$ would make study A appear most effective. Ranking by $OR$ gives approximately the same value for all three.\n\nThe per-study CIs for $OR$:\n\n\n::: {#tbl-study-ci .cell tbl-cap='Per-study 95% CIs for OR via the log-transform delta method.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"euggweygwj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#euggweygwj table {\n  font-family: Lora, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#euggweygwj thead, #euggweygwj tbody, #euggweygwj tfoot, #euggweygwj tr, #euggweygwj td, #euggweygwj th {\n  border-style: none;\n}\n\n#euggweygwj p {\n  margin: 0;\n  padding: 0;\n}\n\n#euggweygwj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#euggweygwj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#euggweygwj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#euggweygwj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#euggweygwj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#euggweygwj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#euggweygwj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#euggweygwj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#euggweygwj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#euggweygwj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#euggweygwj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#euggweygwj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#euggweygwj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#euggweygwj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#euggweygwj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#euggweygwj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#euggweygwj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#euggweygwj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#euggweygwj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#euggweygwj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#euggweygwj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#euggweygwj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#euggweygwj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#euggweygwj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#euggweygwj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#euggweygwj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#euggweygwj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#euggweygwj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#euggweygwj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#euggweygwj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#euggweygwj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#euggweygwj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#euggweygwj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#euggweygwj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#euggweygwj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#euggweygwj .gt_left {\n  text-align: left;\n}\n\n#euggweygwj .gt_center {\n  text-align: center;\n}\n\n#euggweygwj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#euggweygwj .gt_font_normal {\n  font-weight: normal;\n}\n\n#euggweygwj .gt_font_bold {\n  font-weight: bold;\n}\n\n#euggweygwj .gt_font_italic {\n  font-style: italic;\n}\n\n#euggweygwj .gt_super {\n  font-size: 65%;\n}\n\n#euggweygwj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#euggweygwj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#euggweygwj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#euggweygwj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#euggweygwj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#euggweygwj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#euggweygwj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#euggweygwj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#euggweygwj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"study\">Study</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_or\"><span data-qmd-base64=\"JFxsb2coXHdpZGVoYXR7T1J9KSQ=\"><span class='gt_from_md'>\\(\\log(\\widehat{OR})\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se2\"><span data-qmd-base64=\"JFNFXjIk\"><span class='gt_from_md'>\\(SE^2\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\"><span data-qmd-base64=\"JFNFJA==\"><span class='gt_from_md'>\\(SE\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci_lower\">CI lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci_upper\">CI upper</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">A</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2604</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0404</td>\n<td headers=\"se\" class=\"gt_row gt_right\">0.2010</td>\n<td headers=\"ci_lower\" class=\"gt_row gt_right\">0.875</td>\n<td headers=\"ci_upper\" class=\"gt_row gt_right\">1.924</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">B</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2632</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0182</td>\n<td headers=\"se\" class=\"gt_row gt_right\">0.1350</td>\n<td headers=\"ci_lower\" class=\"gt_row gt_right\">0.999</td>\n<td headers=\"ci_upper\" class=\"gt_row gt_right\">1.695</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">C</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2655</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0161</td>\n<td headers=\"se\" class=\"gt_row gt_right\">0.1271</td>\n<td headers=\"ci_lower\" class=\"gt_row gt_right\">1.017</td>\n<td headers=\"ci_upper\" class=\"gt_row gt_right\">1.673</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nStudy A has the widest CI ($SE = 0.201$), driven by the small control positive count $c = 50$: the $\\frac{1}{c}$ term dominates. Study C has the narrowest ($SE = 0.127$), because all four cells are large. Only study C's CI excludes $1$ at the 95% level.\n\n\n## Aggregation: why not merge the tables?\n\nThe three 2×2 tables could be summed cell-by-cell into a single pooled table. The $OR$ computed from that pooled table is the marginal $OR$. If the $OR$ is the same within each study, the marginal $OR$ should recover that common value. It does not.\n\nThe odds ratio is non-collapsible: even when the within-stratum $OR$ is identical across strata and the stratifying variable (here, study) is not a confounder, the marginal $OR$ does not equal the common within-stratum $OR$ (Greenland, Robins, and Pearl 1999). This is a mathematical property of the $OR$, not a data issue.\n\nA numerical example. Two studies, each with $OR = 4.0$ and $n_1 = n_0 = 1{,}000$:\n\n\n::: {#tbl-noncollapse .cell tbl-cap='Non-collapsibility of the OR. Within-study OR is 4.0 for both studies. The marginal OR is 3.22.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ktzymibxvm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#ktzymibxvm table {\n  font-family: Lora, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ktzymibxvm thead, #ktzymibxvm tbody, #ktzymibxvm tfoot, #ktzymibxvm tr, #ktzymibxvm td, #ktzymibxvm th {\n  border-style: none;\n}\n\n#ktzymibxvm p {\n  margin: 0;\n  padding: 0;\n}\n\n#ktzymibxvm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ktzymibxvm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ktzymibxvm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ktzymibxvm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ktzymibxvm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ktzymibxvm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ktzymibxvm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ktzymibxvm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ktzymibxvm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ktzymibxvm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ktzymibxvm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ktzymibxvm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ktzymibxvm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ktzymibxvm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ktzymibxvm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ktzymibxvm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ktzymibxvm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ktzymibxvm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ktzymibxvm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ktzymibxvm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ktzymibxvm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ktzymibxvm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ktzymibxvm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ktzymibxvm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ktzymibxvm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ktzymibxvm .gt_left {\n  text-align: left;\n}\n\n#ktzymibxvm .gt_center {\n  text-align: center;\n}\n\n#ktzymibxvm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ktzymibxvm .gt_font_normal {\n  font-weight: normal;\n}\n\n#ktzymibxvm .gt_font_bold {\n  font-weight: bold;\n}\n\n#ktzymibxvm .gt_font_italic {\n  font-style: italic;\n}\n\n#ktzymibxvm .gt_super {\n  font-size: 65%;\n}\n\n#ktzymibxvm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ktzymibxvm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ktzymibxvm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ktzymibxvm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ktzymibxvm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ktzymibxvm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ktzymibxvm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ktzymibxvm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ktzymibxvm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"study\">Study</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p0\"><span data-qmd-base64=\"JHBfMCQ=\"><span class='gt_from_md'>\\(p_0\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p1\"><span data-qmd-base64=\"JHBfMSQ=\"><span class='gt_from_md'>\\(p_1\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"or\"><span data-qmd-base64=\"JE9SJA==\"><span class='gt_from_md'>\\(OR\\)</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">A</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.100</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.308</td>\n<td headers=\"or\" class=\"gt_row gt_right\">4.000</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">B</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.400</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.727</td>\n<td headers=\"or\" class=\"gt_row gt_right\">4.000</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">Merged</td>\n<td headers=\"p0\" class=\"gt_row gt_right\">0.250</td>\n<td headers=\"p1\" class=\"gt_row gt_right\">0.517</td>\n<td headers=\"or\" class=\"gt_row gt_right\">3.217</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nBoth studies have $OR = 4.0$. The merged table has $p_0 = 0.25$, $p_1 = 0.518$, and $OR = 3.22$. The marginal $OR$ is attenuated toward $1$ even though study is not a confounder. The magnitude of the attenuation depends on how different the baselines are; it vanishes only when all strata share the same $p_0$.\n\n$RR$ and $RD$ do not have this problem. If the within-stratum $RR$ is identical across strata with equal sample sizes, the marginal $RR$ equals the common value. This is collapsibility. The $OR$ lacks it. The consequence: aggregating $OR$ values across studies must be done on the estimates, not on the pooled table. Compute $\\log(\\widehat{OR})$ within each study, then combine.\n\n\n## Pooling study-level log(OR)\n\nThe inverse-variance weighted mean of $\\log(\\widehat{OR})$ across $K$ studies is:\n\n$$\\log(\\widehat{OR})_{\\text{pooled}} = \\frac{\\sum_{k=1}^{K} w_k \\log(\\widehat{OR}_k)}{\\sum_{k=1}^{K} w_k}$$\n\nwhere $w_k = \\frac{1}{\\text{Var}(\\log(\\widehat{OR}_k))} = \\frac{1}{\\frac{1}{a_k} + \\frac{1}{b_k} + \\frac{1}{c_k} + \\frac{1}{d_k}}$.\n\nThe variance of the pooled estimate is $\\text{Var}(\\log(\\widehat{OR})_{\\text{pooled}}) = \\frac{1}{\\sum_{k} w_k}$, and the 95% CI is:\n\n$$\\log(\\widehat{OR})_{\\text{pooled}} \\pm 1.96 \\times \\frac{1}{\\sqrt{\\sum_k w_k}}$$\n\nThis is a fixed-effect model: it assumes the true $\\log(OR)$ is the same across all studies. When study-level effects vary (heterogeneity), a random-effects model adds an inter-study variance component $\\tau^2$ to each $\\text{Var}(\\log(\\widehat{OR}_k))$ before computing the weights. The fixed-effect version is shown here; the extension is mechanical.\n\n### Worked example: pooling the three studies\n\n\n::: {#tbl-pooling .cell tbl-cap='Inverse-variance weighted pooling of three studies.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xuoksvhmmn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#xuoksvhmmn table {\n  font-family: Lora, system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xuoksvhmmn thead, #xuoksvhmmn tbody, #xuoksvhmmn tfoot, #xuoksvhmmn tr, #xuoksvhmmn td, #xuoksvhmmn th {\n  border-style: none;\n}\n\n#xuoksvhmmn p {\n  margin: 0;\n  padding: 0;\n}\n\n#xuoksvhmmn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xuoksvhmmn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xuoksvhmmn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xuoksvhmmn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xuoksvhmmn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xuoksvhmmn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xuoksvhmmn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xuoksvhmmn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xuoksvhmmn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xuoksvhmmn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xuoksvhmmn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xuoksvhmmn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xuoksvhmmn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xuoksvhmmn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xuoksvhmmn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xuoksvhmmn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xuoksvhmmn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xuoksvhmmn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xuoksvhmmn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xuoksvhmmn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xuoksvhmmn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xuoksvhmmn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xuoksvhmmn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xuoksvhmmn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xuoksvhmmn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xuoksvhmmn .gt_left {\n  text-align: left;\n}\n\n#xuoksvhmmn .gt_center {\n  text-align: center;\n}\n\n#xuoksvhmmn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xuoksvhmmn .gt_font_normal {\n  font-weight: normal;\n}\n\n#xuoksvhmmn .gt_font_bold {\n  font-weight: bold;\n}\n\n#xuoksvhmmn .gt_font_italic {\n  font-style: italic;\n}\n\n#xuoksvhmmn .gt_super {\n  font-size: 65%;\n}\n\n#xuoksvhmmn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xuoksvhmmn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xuoksvhmmn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xuoksvhmmn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xuoksvhmmn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xuoksvhmmn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xuoksvhmmn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xuoksvhmmn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xuoksvhmmn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"study\">Study</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_or\"><span data-qmd-base64=\"JFxsb2coXHdpZGVoYXR7T1J9KSQ=\"><span class='gt_from_md'>\\(\\log(\\widehat{OR})\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se2\"><span data-qmd-base64=\"JFNFXjIk\"><span class='gt_from_md'>\\(SE^2\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"w\"><span data-qmd-base64=\"JHck\"><span class='gt_from_md'>\\(w\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"w_log_or\"><span data-qmd-base64=\"JHcgXHRpbWVzIFxsb2coXHdpZGVoYXR7T1J9KSQ=\"><span class='gt_from_md'>\\(w \\times \\log(\\widehat{OR})\\)</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">A</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2604</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0404</td>\n<td headers=\"w\" class=\"gt_row gt_right\">24.7625</td>\n<td headers=\"w_log_or\" class=\"gt_row gt_right\">6.4488</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">B</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2632</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0182</td>\n<td headers=\"w\" class=\"gt_row gt_right\">54.8677</td>\n<td headers=\"w_log_or\" class=\"gt_row gt_right\">14.4435</td></tr>\n    <tr><td headers=\"study\" class=\"gt_row gt_right\">C</td>\n<td headers=\"log_or\" class=\"gt_row gt_right\">0.2655</td>\n<td headers=\"se2\" class=\"gt_row gt_right\">0.0161</td>\n<td headers=\"w\" class=\"gt_row gt_right\">61.9507</td>\n<td headers=\"w_log_or\" class=\"gt_row gt_right\">16.4510</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n$$\\sum w_k = 141.58, \\quad \\log(\\widehat{OR})_{\\text{pooled}} = \\frac{37.3433}{141.58} = 0.2638$$\n\n$$SE_{\\text{pooled}} = \\frac{1}{\\sqrt{141.58}} = 0.0840$$\n\n$$\\text{95% CI for } \\log(OR): \\quad 0.2638 \\pm 1.96 \\times 0.0840 = (0.0990, \\; 0.4285)$$\n\n$$\\text{95% CI for } OR: \\quad (e^{0.0990}, \\; e^{0.4285}) = (1.104, \\; 1.535)$$\n\nNone of the three individual studies produced a CI that cleanly excluded $1$ at the 95% level (only study C barely did). The pooled CI excludes $1$, with a lower bound above $1.1$. Aggregation recovered the signal that the individual studies could not establish alone.\n\nStudy C receives the largest weight ($w_C$) because its four cells are all large, producing the smallest variance. Study A receives the smallest weight: its control positive count $c = 50$ inflates the $\\frac{1}{c}$ term. The weights automatically downweight less precise estimates, without any manual judgment about which studies to include.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Per-study and pooled 95% CIs for OR.](index_files/figure-html/fig-pooled-ci-1.png){#fig-pooled-ci width=672}\n:::\n:::\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}